package com.tico.pomorodo.ui.theme

const val IC_BOTTOM_TIMER = "ic_bottom_timer"
const val IC_BOTTOM_TODO = "ic_bottom_todo"
const val IC_BOTTOM_FOLLOW = "ic_bottom_follow"
const val IC_BOTTOM_MY_INFO = "ic_bottom_my_info"

const val BG_CIRCULAR_TIMER = "bg_circular_timer"

const val IC_ARROW_FRONT = "ic_arrow_front"
const val IC_ARROW_BACK = "ic_arrow_back"
const val IC_CALENDAR_DROP_DOWN = "ic_calendar_drop_down"
const val IC_ADD_TODO = "ic_add_todo"
const val IC_TODO_UNCHECKED = "ic_todo_unchecked"
const val IC_TODO_CHECKED = "ic_todo_checked"
const val IC_TODO_GOING = "ic_todo_going"
const val IC_TODO_MORE_INFO = "ic_todo_more_info"
const val IC_MORE_INFO = "ic_more_info"
const val IC_ADD_CATEGORY = "ic_add_category"
const val IC_CALENDAR_DATE_WHITE = "ic_calendar_date_white"
const val IC_CALENDAR_DATE_GREEN = "ic_calendar_date_green"
const val IC_CALENDAR_DATE_YELLOW = "ic_calendar_date_yellow"
const val IC_CALENDAR_DATE_ORANGE = "ic_calendar_date_orange"
const val IC_CALENDAR_DATE_RED = "ic_calendar_date_red"

const val IC_OK = "ic_ok"
const val IC_UNOK = "ic_unok"
const val IC_DROP_DOWN = "ic_drop_down"
const val IC_DROP_DOWN_DISABLE = "ic_drop_down_disable"
const val IC_CATEGORY_FULL_OPEN = "ic_category_full_open"
const val IC_CATEGORY_FOLLOWER_OPEN = "ic_category_follower_open"
const val IC_CATEGORY_GROUP_OPEN = "ic_category_group_open"
const val IC_CATEGORY_ONLY_ME_OPEN = "ic_category_only_me_open"
const val IC_SELECTED_GROUP_MEMBER_CANCEL = "ic_selected_group_member_cancel"
const val IC_GROUP_SELECTED_UNCHECKED = "ic_group_selected_unchecked"
const val IC_ARROW_RIGHT = "ic_arrow_right"
const val IC_ALL_CLEAN = "ic_all_clean"

const val IC_TIMELINE_MORE_INFO = "ic_timeline_more_info"

const val IC_ALARM_OPTION_SOUND = "ic_alarm_option_sound"
const val IC_ALARM_OPTION_VIBRATE = "ic_alarm_option_vibrate"
const val IC_ALARM_OPTION_MUTE = "ic_alarm_option_mute"

const val IC_SEARCH = "ic_search"